apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: deepshield
resources:
  - namespace.yaml
  - backend-configmap.yaml
  - backend-secret.example.yaml
  - backend-deployment.yaml
  - frontend-deployment.yaml
